#!/bin/bash

python test_phn.py --test-instance-name bar-n100-1 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n100-1 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n100-1 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n100-1 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n100-2 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n100-2 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n100-2 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n100-2 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n100-3 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n100-3 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n100-3 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n100-3 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n100-4 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n100-4 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n100-4 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n100-4 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n100-5 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n100-5 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n100-5 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n100-5 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n100-6 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n100-6 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n100-6 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n100-6 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-1 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-1 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-1 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-1 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-2 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-2 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-2 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-2 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-3 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-3 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-3 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-3 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-4 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-4 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-4 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-4 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-5 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-5 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-5 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-5 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-6 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-6 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-6 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n200-6 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-1 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-1 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-1 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-1 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-2 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-2 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-2 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-2 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-3 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-3 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-3 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-3 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-4 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-4 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-4 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-4 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-5 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-5 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-5 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-5 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-6 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-6 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-6 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name bar-n400-6 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-1 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-1 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-1 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-1 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-2 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-2 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-2 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-2 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-3 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-3 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-3 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-3 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-4 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-4 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-4 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-4 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-5 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-5 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-5 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-5 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-6 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-6 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-6 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n100-6 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-1 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-1 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-1 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-1 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-2 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-2 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-2 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-2 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-3 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-3 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-3 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-3 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-4 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-4 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-4 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-4 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-5 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-5 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-5 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-5 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-6 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-6 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-6 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n200-6 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-1 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-1 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-1 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-1 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-2 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-2 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-2 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-2 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-3 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-3 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-3 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-3 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-4 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-4 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-4 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-4 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-5 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-5 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-5 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-5 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-6 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-6 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-6 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name ber-n400-6 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-1 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-1 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-1 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-1 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-2 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-2 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-2 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-2 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-3 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-3 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-3 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-3 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-4 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-4 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-4 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-4 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-5 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-5 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-5 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-5 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-6 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-6 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-6 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n100-6 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-1 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-1 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-1 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-1 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-2 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-2 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-2 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-2 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-3 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-3 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-3 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-3 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-4 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-4 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-4 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-4 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-5 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-5 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-5 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-5 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-6 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-6 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-6 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n200-6 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-1 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-1 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-1 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-1 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-2 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-2 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-2 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-2 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-3 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-3 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-3 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-3 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-4 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-4 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-4 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-4 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-5 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-5 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-5 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-5 --test-num-vehicles 10 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-6 --test-num-vehicles 1 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-6 --test-num-vehicles 3 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-6 --test-num-vehicles 5 --title moco-hnc --num-ray 200
python test_phn.py --test-instance-name poa-n400-6 --test-num-vehicles 10 --title moco-hnc --num-ray 200